[package]
name = "chip8pc"
version = "0.1.0"
authors = ["Yushi Omote <yushiomote@gmail.com>"]
edition = "2018"

[dependencies]
x86_64 = "0.3.4"
log = { version = "0.4", default-features = false }
rand = { version = "0.6", default-features = false }
libchip8 = "0.1.2"
